### ACTORS INDEX
GET http://localhost:3000/actors.json 

### ACTORS CREATE

POST http://localhost:3000/actors.json 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzYwNjM5MzJ9.z5Q1kMK0CVbuTdgA-Gz5rzBLHMyZLJMTjMwIgH0AqJc
Content-Type: application/json

{
  "first_name": "Kevin",
  "last_name": "Smith",
  "known_for": "Clerks",
  "gender": "male",
  "age": 51
}

### ACTORS SHOW
GET http://localhost:3000/actors/7.json

### ACTORS UPDATE
PATCH http://localhost:3000/actors/1.json
Content-Type: application/json

{
  "gender": "male",
  "age": 51
}

### ACTORS DESTROY

DELETE http://localhost:3000/actors/5.json

### MOVIES INDEX
GET http://localhost:3000/movies.json

### MOVIES CREATE
POST http://localhost:3000/movies.json
Content-Type: application/json

{
  "title": "The Texas Chain Saw Massacre",
  "year": 1974,
  "plot": "The film follows a group of friends who fall victim to a family of cannibals while on their way to visit an old homestead.",
  "director": "Tobe Hooper",
  "english": "english"
}

### MOVIES SHOW
GET http://localhost:3000/movies/1.json

### MOVIES UPDATE
PATCH http://localhost:3000/movies/2.json
Content-Type: application/json

{
  "director": "John Carpenter",
  "english": "english"
}

### MOVIES DESTROY
DELETE http://localhost:3000/movies/12.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzYwNjM4MDB9.4aPPKPb-NRvmqkuJVNytExKc2cJr-QRDS7IV8br7Pig


### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Philip",
  "email": "phil@example.com",
  "password": "password1",
  "password_confirmation": "password1"
}


### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "phil@example.com",
  "password": "password1"
}
