### ACTORS INDEX
GET http://localhost:3000/actors.json 

### ACTORS CREATE

POST http://localhost:3000/actors.json 
Content-Type: application/json

{
  "first_name":
  "last_name":
  "known_for":
}

### ACTORS SHOW
GET http://localhost:3000/actors/7.json

### ACTORS UPDATE
PATCH http://localhost:3000/actors/7.json
Content-Type: application/json

{

}

### ACTORS DESTROY

DELETE http://localhost:3000/actors/7.json

### MOVIES INDEX
GET http://localhost:3000/movies.json

### MOVIES CREATE
POST http://localhost:3000/movies.json
Content-Type: application/json

{
  "title": "The Texas Chain Saw Massacre",
  "year": 1974,
  "plot": "The film follows a group of friends who fall victim to a family of cannibals while on their way to visit an old homestead.",
  "director": "Tobe Hooper",
  "english": "english"
}

### MOVIES SHOW
GET http://localhost:3000/movies/1.json

### MOVIES UPDATE
PATCH http://localhost:3000/movies/1.json
Content-Type: application/json

{

}

### MOVIES DESTROY
DELETE http://localhost:3000/movies/4.json